### ISSUE TITLE
Updating Muscle Torques mid-simulation - how does it work?

### ISSUE THREAD

**Issue by saultshaker** [GazzolaLab/Elastica-RL-control#11]
I am trying to build a custom gymnasium environment for my own RL project using PyElastica.

I've been digging into the [`muscle_torques_with_bspline.py`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/MuscleTorquesWithBspline/BsplineMuscleTorques/muscle_torques_with_bspline.py#L11) for Case 1 to try and understand the nuts and bolts of how muscle torques are changing mid-simulation. 

In an attempt to compare it with a PyElastica example were forces/torques applied to rods aren't changing throughout the simulation, I looked at [`axial_stretching.py`](https://github.com/GazzolaLab/PyElastica/blob/master/examples/AxialStretchingCase/axial_stretching.py) which brought me to the [EndPointForces class](https://github.com/GazzolaLab/PyElastica/blob/11fe8e96ac78fdc1fa4d0ce5bf61bb427afb8875/elastica/external_forces.py#L119). 

I am still not clear how `muscle_torques_with_bspline.py` allows for an RL agent to change the torques within a rod while the simulation is running. Could this be explained?

I'm happy to provide additional details to clarify my question if that's useful. 

Thanks in advance!

**Comment by Ali-7800** [comment]
Hi @saultshaker,

Nothing in the classes themselves that is changing muscle torques mid-simulation, what is happening is that we change the value of the inputs to the classes during the timestepping. If you look at set_environment.py in the step method we change spline_points_func_array_normal_dir using the action from the RL agent, note that we don't redefine spline_points_func_array_normal_dir but rather change the values in the array so it is the same input we gave to the MuscleTorquesWithVaryingBetaSplines class but with a different value value.

Let me know if that makes sense!

**Comment by saultshaker** [comment]
Hi @Ali-7800 

Thank you for your response! I am still trying to understand this a bit better. A few questions:

1. I noticed that [`self.simulator.finalize()`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/set_environment.py#L831) is called as part of the reset() method. My naive understanding is that the reset() method is called once per episode, and that the finalize() method prevents changes to a PyElastica simulation. How does updating the values of  spline_points_func_array_normal_dir in the step() method update the muscle torques when MuscleTorquesWithBetaSplines is called in the reset() method as part of  [`self.simulator.add_forcing_to(self.shearable_rod)`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/set_environment.py#L533C1-L533C1)?

2. Is [`self.simulator.add_forcing_to(self.shearable_rod)`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/set_environment.py#L533C1-L533C1) called and/or updated every step so that the updated values assigned by the RL agent affect the simulation? 
 
3. Is it important that the [`MuscleTorquesWithVaryingBetaSplines`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/MuscleTorquesWithBspline/BsplineMuscleTorques/muscle_torques_with_bspline.py) class is module that is imported to the [`set_environment.py`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/set_environment.py) file? Is that required for it to play nice and update with the RL agent?

Thank you so much for your time on this!

**Comment by Ali-7800** [comment]
Hi @saultshaker,

1. The finalize() method prevents changes like adding a rod, a forcing class, a connection, etc. However, that does not mean you cannot modify already existing parts of the simulation like spline_points_func_array_normal_dir. The reset() method sets up the simulation each episode while the step() method does the time stepping for each episode and while timestepping it modifies spline_points_func_array_normal_dir.

2. No this is only called with each reset(), In each do_step() in step() it calls the apply_forces() and apply_torques() methods of the class you already added with [`self.simulator.add_forcing_to(self.shearable_rod)`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/set_environment.py#L533C1-L533C1) in reset(). 

3. It does not have to be imported into the file, you can move it in [`set_environment.py`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case3/ReacherSoft_Case3_main-text/set_environment.py) and it should still work.

**Comment by saultshaker** [comment]
Hi @Ali-7800,

Thank you so much for this! I've been so busy with all of my code working because of the wonderful feedback you provided that I forgot to close out this issue. Thank you again, this was tremendously helpful!
