### ISSUE TITLE
Which CoRL 2020 paper is Case 1 based on?

### ISSUE THREAD

**Issue by saultshaker** [GazzolaLab/Elastica-RL-control#12]
In Case 1, the [`__doc__`](https://github.com/GazzolaLab/Elastica-RL-control/blob/1e708f889b81c572ba4d78d2df7213688e0e7ee3/Case1/logging_bio_args.py#L1) string states that

>  This script is to train or run a policy for the arm following randomly moving target. Case 1 in CoRL 2020 paper.

I'm assuming CoRL is "Conference on Robot Learning". 

Looking at the references for the [Naughton et al., RA-L, 2021](https://ieeexplore.ieee.org/document/9369003/references) paper, I don't see any CoRL 2020 papers. 

I also checked the [wonderful supplementary materials website](https://www.cosseratrods.org/Elastica+RL/#case-1-3d-tracking-of-a-randomly-moving-target) as well as tried searching through this [archive of CoRL 2020 papers](https://corlconf.github.io/corl2020/) but to no avail. 

Thanks in advance for pointing me in the right direction!

**Comment by armantekinalp** [comment]
There is a mistake in documentation it is the Naughton et. al. RA-L 2021 paper.

**Comment by saultshaker** [comment]
Ah, that makes sense. Thank you!
