### ISSUE TITLE
Applying new force in step method

### ISSUE THREAD

**Issue by davenpi** [GazzolaLab/Elastica-RL-control#4]
Hi all,

I'm building a custom RL env to do some learning tasks with soft filaments in PyElastica. I'm running into trouble applying new actions and I was looking over the Case 1 code for some guidance on how I might do that. One of the points that I am confused about is how you apply a new action when you call the `step` method of the env. The `reset` method finalizes the simulator and my understanding is that after finalization no new forces can be added. Is the point that no new forces can be added but we can change the magnitude of the forces/torques already there? In other words, how is the `step` method applying a new force without resetting the environment?

Thanks

**Comment by armantekinalp** [comment]
Hi @davenpi ,

In the `step` method we are passing the `action`, and `action` array contains the control points for muscle torque spline. As you can see in [`step`](https://github.com/GazzolaLab/Elastica-RL-control/blob/main/Case1/set_environment.py#L701) method, we pass the numbers inside the `action` to the [`spline_points_func_array_*`](https://github.com/GazzolaLab/Elastica-RL-control/blob/main/Case1/set_environment.py#L729) . Note that  `spline_points_func_array_*` is a NumPy array and initialize in the `reset` method, and we are only changing the entries of the array. 

So you don't need to `reset` the environment to change the forces, you only need to update the `action`.

**Comment by davenpi** [comment]
Hi @armantekinalp 

Thanks for the response. The issue I was having turned out to be an action space sampling issue. I thought I wasn't able to specify new actions but actually it was just that the policy kept picking the same action. Once I normalized the action space as indicated in the [SB3 docs](https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html) (and [this issue](https://github.com/DLR-RM/stable-baselines3/issues/389)) things started working as expected. Thanks again.
