### ISSUE TITLE
MuscleTorqueWithVaryingBSpline

### ISSUE THREAD

**Issue by ajaigit** [GazzolaLab/Elastica-RL-control#5]
Hello PyElastica,

I really appreciate you guys for taking the time to resolve our queries. After taking the steps you mentioned in my issue titled " **Generating Data From Trained Model** ", I wanted to use MuscleTorqueWithVaryingBSpline and generate some data, and to do that I am using the code in the uploaded file.
[Practice1.txt](https://github.com/GazzolaLab/Elastica-RL-control/files/7855791/Practice1.txt)
But I run into the following error :  
`Traceback (most recent call last):
  File "Practice1.py", line 199, in <module>
    integrate(timestepper, ElasticaSim, final_time, total_steps)
  File "C:\Users\reach\anaconda3\envs\MyEnv\lib\site-packages\elastica\_elastica_numba\_timestepper\__init__.py", line 79, in integrate
    time = do_step(StatefulStepper, stages_and_updates, System, time, dt)
  File "C:\Users\reach\anaconda3\envs\MyEnv\lib\site-packages\elastica\timestepper\symplectic_steppers.py", line 83, in do_step
    SystemCollection.synchronize(time)
  File "C:\Users\reach\anaconda3\envs\MyEnv\lib\site-packages\elastica\wrappers\base_system.py", line 158, in synchronize
    feature(self, time)
  File "C:\Users\reach\anaconda3\envs\MyEnv\lib\site-packages\elastica\wrappers\forcing.py", line 84, in __call__
    ext_force_torque.apply_torques(self._systems[sys_id], time, *args, **kwargs)
  File "C:\Users\reach\Desktop\Thesis\Elastica-RL-control-main\Case1\MuscleTorquesWithBspline\BsplineMuscleTorques\muscle_torques_with_bspline_numba.py", line 145, in apply_torques
    self.max_rate_of_change_of_activation,
ValueError: unable to broadcast argument 1 to output array
File "C:\Users\reach\anaconda3\envs\MyEnv\lib\site-packages\numba\np\npyimpl.py", line 228,`

Any advice into this will be of great help

Thank you.

**Comment by nmnaughton** [comment]
Hi @ajaigit ,

You need to update the action arrays before running the simulation. For example, you define `spline_points_func_array_normal_dir = []` during setup, so you are only passing an empty array of actions to `MuscleTorqueWithVaryingBSpline` which is why you are getting the error. Adding 

```
spline_points_func_array_normal_dir[:] = np.zeros(spline_points_func_array_normal_dir)
spline_points_func_array_twist_dir[:] = np.zeros(spline_points_func_array_normal_dir)
spline_points_func_array_binormal_dir[:] = np.zeros(spline_points_func_array_normal_dir)
```

before you run the simulation will set all the actions to zero (or set the arrays to whatever you want).

**Comment by ajaigit** [comment]
Thank you for the response. I replaced the empty list with a random vector of size (6,1).  Unfortunately, that did not work out for me and the execution of the script ended up with an error. I am pretty sure that the error is probably because of my poor understanding about the working of Muscle Torques being used  so I still have a couple of questions about MuscleTorqueWithVaryingBSpline: 
1. What purpose do `spline_points_func_array_normal_dir` and similarly spline_points_func_arrary in other direction ?
2. Does the RL algorithm randomly choose the magnitude of torque required or does it select from a predefined set of torques that it can choose from?
3. Is it possible to manually select the control points and then apply a torque of a given magnitude say 2 N-m and then observe the effect on the robot change in configuration?
Thank you.

**Comment by nmnaughton** [comment]
The following script works for me. All I did was update the arrays with zeros. However, I noticed that you need to use pyelastica<=0.1.0.post5. The recent updates to v0.2.0 lead to breaking changes. They are minor so I will look into pushing a fix. 
[Practice1.txt](https://github.com/GazzolaLab/Elastica-RL-control/files/7883207/Practice1.txt)

To answer your questions:
1. `spline_points_func_array_normal_dir` are where you put the appropriate actions for the torques in that direction. In 3D you  have a total action space of 2*num_control_points. You then need to place half the actions into 1 array and half into the other so pyelastica can use them to compute the torque on the arm. Pyelastica then computes a torque spline that is distributed along the arm and applies this torque to the arm. 

2. This depends on what RL algorithm you use. In our paper, we used multiple continuous action algorithms from stable baselines so each action could be continuous between -1 and 1. However, Pyelastica doesn't really care if the value is continuous or not so if you implement a discrete action space method I don't foresee any issues. 

3. Your Practice.txt script can do this very easily. In the updated script, the action arrays are all zeros so no torque is being applied. Just change one or more index to between [-1, 1]. The total torque applied is scaled by alpha, so if you want a max torque of 2 Nm, just set alpha=2.

**Comment by nmnaughton** [comment]
@ajaigit we updated the main branch so you should now be able to use it with the latest version of pyelastica if that is useful. I am going to close this issue, but if you have any more questions please open a new issue and ask!

best,
Noel
